print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/justinb/Documents/repo_pinball/UHPinball/Pinball/Assets/Prefabs/pinball paddles.mb"`)
{		
	file -o "/Users/justinb/Documents/repo_pinball/UHPinball/Pinball/Assets/Prefabs/pinball paddles.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/justinb/Documents/repo_pinball/UHPinball/Pinball/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/justinb/Documents/repo_pinball/UHPinball/Pinball/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/justinb/Documents/repo_pinball/UHPinball/Pinball/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
